version: 2
jobs:
  build:
    machine:
      image: ubuntu-2204:2023.07.2
    resource_class: large
    steps:
      - checkout
      - run: |
          sudo ./build.sh "$CERT_FULLCHAIN_URL" "$CERT_PRIVKEY_URL"
      - run:
          no_output_timeout: 30m
          command: sudo ./publish.sh "$DOCKER_USER" "$DOCKER_PASS" "$CIRCLE_BUILD_NUM"
